class TopicsMap {
  static Map<String, String> topicMapping = {
    "Arts and Culture": "Culture",
    "Business": "Business",
    "Crime": "Crime",
    "Education": "Education",
    "Entertainment": "Entertainment",
    "Environment": "Environment",
    "Fashion": "Fashion",
    "Finance": "Finance",
    "Food and Dining": "Food",
    "Health": "Health",
    "Human Interest": "Interest",
    "Lifestyle": "Lifestyle",
    "Opinion Editorial": "Opinion",
    "Politics": "Politics",
    "Real Estate": "House",
    "Science": "Science",
    "Sports": "Sports",
    "Technology": "Technology",
    "Travel": "Travel",
    "Automotive": "Automotive",
    "Books": "Culture",
    "Movies": "Entertainment",
    "Music": "Entertainment",
    "Photography": "Culture",
    "Gaming": "Entertainment",
    "Fitness": "Health",
    "Nature": "Environment",
    "Wellness": "Health",
    "Startups": "Business",
    "Gadgets": "Technology",
    "Artificial Intelligence": "Technology",
    "Space": "Science",
    "Robotics": "Technology",
    "Astronomy": "Science",
    "Medicine": "Health",
    "Mental Health": "Health",
    "Nutrition": "Health",
    "Psychology": "Health",
    "Economics": "Finance",
    "Investment": "Finance",
    "Personal Finance": "Finance",
    "Cryptocurrency": "Finance",
    "Parenting": "Lifestyle",
    "Home Improvement": "House",
    "Pets": "Lifestyle",
    "Social Media": "Technology",
    "Startups": "Business",
    "World News": "Politics",
    "Local News": "Interest",
  };
}
