class NewsArticle {
// Optional, as it will be generated by the backend
  final String sourceName;
  final String author;
  final String title;
  final String description;
  final String url;
  final String urlToImage;
  final String publishedAt;
  final String content;
  final bool liked;
  final bool bookmarked;

  NewsArticle({
    // Id is optional here, as it will be set by the backend
    required this.sourceName,
    required this.author,
    required this.title,
    required this.description,
    required this.url,
    required this.urlToImage,
    required this.publishedAt,
    required this.content,
    this.liked = false,
    this.bookmarked = false,
  });

  factory NewsArticle.fromJson(Map<String, dynamic> json) {
    return NewsArticle(
      sourceName: json['source']['name'] ?? 'Unknown Source',
      author: json['author'] ?? 'Unknown Author',
      title: json['title'] ?? '',
      description: json['description'] ?? '',
      url: json['url'] ?? '',
      urlToImage: json['urlToImage'] ??
          'https://i0.wp.com/sunrisedaycamp.org/wp-content/uploads/2020/10/placeholder.png?ssl=1',
      publishedAt: json['publishedAt'] ?? '',
      content: json['content'] ?? '',
    );
  }

  factory NewsArticle.fromSharedJson(Map<String, dynamic> json) {
    final newsData = json['news_id']; // Correcting the nested JSON key

    return NewsArticle(
      sourceName: newsData['source_name'] ?? 'Unknown Source',
      author: newsData['author'] ?? 'Unknown Author',
      title: newsData['title'] ?? '', // Corrected key
      description: newsData['description'] ?? '',
      url: newsData['url'] ?? '',
      urlToImage: newsData['url_to_image'] ??
          'https://i0.wp.com/sunrisedaycamp.org/wp-content/uploads/2020/10/placeholder.png?ssl=1',
      publishedAt: newsData['published_at'] ?? '',
      content: newsData['content'] ?? '',
    );
  }

  factory NewsArticle.fromDaguJson(Map<String, dynamic> json) {
    return NewsArticle(
      sourceName: json['news']['source_name'] ?? 'Unknown Source',
      author: json['news']['author'] ?? 'Unknown Author',
      title: json['news']['author'] ?? '',
      description: json['news']['description'] ?? '',
      url: json['news']['url'] ?? '',
      urlToImage: json['news']['url_to_image'] ??
          'https://i0.wp.com/sunrisedaycamp.org/wp-content/uploads/2020/10/placeholder.png?ssl=1',
      publishedAt: json['news']['published_at'] ?? '',
      content: json['news']['content'] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      "source_name": sourceName,
      "author": author,
      "title": title,
      "description": description,
      "url": url,
      "url_to_image": urlToImage,
      "published_at": publishedAt,
      "content": content,
    };
  }
}
